* ClassicalGSG: Prediction of logP Using Classical Molecular Dynamics Atomic Attributes and  Geometric Scattering Graphs

This project is the implementation of a method called ~ClassicalGSG~
and has introduced in ~paper~.  In this project, we aim to predict the
partition coefficient value for the small molecules.

We employ atomic attributes that are typically used to describe atoms
in molecular dynamics simulations. These atomic attributes are
generated using two classical molecular dynamics force fields
generator tool [[https://cgenff.umaryland.edu][CGenFF]] and [[https://ambermd.org/AmberTools.php][Ambertools]].

These atomic attributes are transformed into index-variant molecular
features using a recently developed method called [[https://arxiv.org/abs/1810.03068][Geometric Scattering
for Graphs]] (GSG).  We train ClassicalGSG logP predictor models
with neural networks (NNs) are implemented using [[https://pytorch.org][PyTorch]].  framework.


* Installation

To install from local repository:

#+BEGIN_SRC bash
  pip install -e .
#+END_SRC


* Usage
To use our ClassicalGSG logP predictor model run the following command:

#+BEGIN_SRC bash
 python -m classicalgsg.LogpPredictor molecule.mol2 molecule.str
#+END_SRC

You can generate CGenFF parameter files for your molecule using CGenFF
online server.
